### ISSUE TITLE
Add possibility to swipe to next/previous tab

### ISSUE THREAD

**Issue by bluezed** [doubleangels/NextDNSManager#104]
It would be nice if it was possible to swipe left/right to get to the next/previous tab. For example to change between Logs and Settings and so on.

On a side-note, when I'm in the Logs section and turn the auto-refresh on then swiping left/right actually moves the list view and a horizontal scroll bar appears. I guess that's not meant to happen?

![Screenshot_2024-02-15-19-02-00-390_com doubleangels nextdnsmanagement](https://github.com/doubleangels/NextDNSManager/assets/3831765/02ae686f-7a4d-42de-9f60-8c5d0280bcde)

**Comment by doubleangels** [comment]
This bug has been fixed as of a485d868e4d7748266adc0015feb7de2a944ee19, and will be included in the next release. Swipe to change tab will be evaluated for a future release.

**Comment by bluezed** [comment]
@doubleangels just got the update to 4.10.3 but the horizontal scrolling still happens though.
As I mentioned before, it only happens when the auto-refresh at the top is switched on. 
Let me know if you need any more info...

**Comment by doubleangels** [comment]
Thank you! I was unable to reproduce the problem on any of my testing devices, what device are you using again?

**Comment by bluezed** [comment]
It's a stock Xiaomi Mi Note 10 Lite (MIUI 13.0.6, Android 12).

**Comment by doubleangels** [comment]
Thank you for the info, I'll do some more investigating. :)

**Comment by bluezed** [comment]
@doubleangels I just noticed that the horizontal scroll issue actually happens on the website in the browser as well, Chrome and Firefox. I assume you're using a web view so that probably has the same "issue" then...

**Comment by doubleangels** [comment]
I am using a web view, thanks for the additional info!

**Comment by doubleangels** [comment]
@bluezed In the current beta versions, I have moved from WebView to GeckoView. I am still unable to reproduce this behavior. Would you be willing to try 5.0.0-beta5 (rolling out soon) and let me know if it still happens for you? Thanks!

**Comment by bluezed** [comment]
@doubleangels I just tried with 5.0.0-beta5 and unfortunately it's still doing it, although not as easy to reproduce as with the previous version, see screenshot below...
As mentioned before it only can be done when the Auto-refresh arrows/circle at the top is active.

Since this also happens with actual browsers I guess there isn't much you can do about it...

Maybe switching to the API would be an odea, though probably too much effort just for this minor issue...

Thanks though for the effort so far!


![Screenshot_2024-03-19-06-35-44-299_com doubleangels nextdnsmanagement](https://github.com/doubleangels/NextDNSManager/assets/3831765/d53aa1bf-c464-4d81-938b-8c4f3e8aacad)

**Comment by doubleangels** [comment]
Weird, thanks for the testing support haha! Yes, using the API is something that's on the roadmap but I don't have the time for that at the moment. I'll leave this issue open and shelved.

**Comment by doubleangels** [comment]
Unfortunately, due to performance issues I've had to scrap the change to GeckoView, so swiping to change tags probably won't come to the app. Sorry about that!
