### ISSUE TITLE
[Bug/Issue] 5.4.3 Update Breaks Dark Mode

### ISSUE THREAD

**Issue by doubleangels** [doubleangels/nextdnsmanager#370]
### FAQ's Checked

Yes

### Severity

Low

### Describe the Issue

The 5.4.3 update breaks Dark Mode switching! Revert lifecycle handler, please!

**Comment by doubleangels** [comment]
Fixed with #373.

**Comment by doubleangels** [comment]
This is unfortunately still an issue in 5.4.4.

**Comment by doubleangels** [comment]
Fixed with #377.

**Comment by doubleangels** [comment]
Unfortunately this is still present in 5.4.6.

**Comment by doubleangels** [comment]
This issue has finally been fixed in commit f88ebd34011022be11d40f4b96b4cbb717136a73.

**Comment by SteX986** [comment]
Hi! Issue is still present on 5.4.9
Forcing dark mode in app settings is not respected :-(

Galaxy S24
Android 14 (stock)
